#!/usr/bin/env node
/**
 * Single-producer version SSOT. Reads the ONE source of truth — the root
 * package.json `version` — and writes the generated `CLAUDEXOR_VERSION`
 * constant that the CLI banner / --version, generated plugin shims, MCP/ACP
 * servers, and adapter manifests all import. It also projects the version into
 * the two tracked distribution descriptors that cannot import TypeScript:
 * server.json and the portable Copilot plugin manifest. Changesets keeps the
 * workspace manifests in lockstep (`fixed`); the docs-truth and release parity
 * gates enforce that every projection matches the root version.
 *
 *   node scripts/gen-version.mjs   # regenerate after bumping the root version
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const rootPkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const version = rootPkg.version;
if (typeof version !== "string" || version.trim() === "") {
  throw new Error("root package.json has no version string");
}

const out = join(root, "packages", "util", "src", "version.ts");
const body = `// GENERATED by scripts/gen-version.mjs from the root package.json — do not edit by hand.
// Run \`pnpm gen:version\` after bumping the root version (changesets keeps the
// workspace manifests in lockstep). The docs-truth gate enforces parity.
export const CLAUDEXOR_VERSION = ${JSON.stringify(version)};
`;
writeFileSync(out, body);

const jsonVersionPaths = [
  join(root, "server.json"),
  join(root, "plugins", "copilot", "plugin.json"),
];
// These files are hand-maintained and Prettier-formatted; only their version
// strings are generated. Re-serializing the parsed object would reflow every
// array Prettier keeps on one line, so `pnpm format:check` failed on every
// release. Replace the version VALUES in place and leave the rest of the
// bytes untouched.
for (const path of jsonVersionPaths) {
  const text = readFileSync(path, "utf8");
  const previous = JSON.parse(text).version;
  const updated = text
    .split(`"version": ${JSON.stringify(previous)}`)
    .join(`"version": ${JSON.stringify(version)}`);
  const parsed = JSON.parse(updated);
  const stale =
    parsed.version !== version || (parsed.packages ?? []).some((pkg) => pkg.version !== version);
  if (stale) {
    throw new Error(
      `gen-version: ${path} still carries a version other than ${version} after substitution — ` +
        `its version strings are not in lockstep, fix the file by hand`,
    );
  }
  writeFileSync(path, updated);
}

process.stdout.write(`Wrote CLAUDEXOR_VERSION="${version}" and portable distribution versions\n`);
